version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - 3000:3000 # application
      - 5555:5555 # prisma studio
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: challenge

volumes:
  mongodb_data:
    driver: local
